name: AckGenExample

settings:
  base:
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 99999

packages:
  AckGen:
    path: ..
    from: 0.1.0
  DataCompression:
    url: https://github.com/mw99/DataCompression
    from: 3.6.0

fileGroups:
  - project.yml

targets:
  AckGenExample:
    sources:
      - Sources
      - path: PackageLicenses.plist
      - path: Settings.bundle
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    preBuildScripts:
      - path: ackgen.sh
        name: "AckGen"
      - path: ackgen_settings.sh
        name: "AckGen Settings Bundle"
    settings:
      base:
        GENERATE_INFOPLIST_FILE: true
        PRODUCT_BUNDLE_IDENTIFIER: com.example.ackgen
    info:
      path: Info.plist
      properties:
        UILaunchScreen:
        UIRequiresFullScreen: true
        CFBundleDisplayName: AckGen
        NSLocationWhenInUseUsageDescription: Example Usage
        NSMicrophoneUsageDescription: Example Usage
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    dependencies:
      - package: AckGen
        product: AckGenUI
      - package: AckGen
        product: ackgen
